[project]
name = "pi_one_minted" # change this to a package name for your plugin
version = "0.0.1"
dependencies = ["pygments"]
readme = "README.md"

[project.entry-points."pygments.styles"]
pi-one-style = "pi_one_style:PiOneStyle"
